apiVersion: v1
kind: Pod
metadata:
  name: py3numpy
spec:
  containers:
  - command:
    command:
      - sh
      - -c
      - 'while true; do sleep 1; done'
    image: gcr.io/aronchick-apollobit/py3numpy:v1.0
    imagePullPolicy: IfNotPresent
    name: py3numpy
