apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra-data
  name: cassandra-data
spec:
  clusterIP: None
  ports:
    - port: 9042
  selector:
    app: cassandra-data
----
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra-analytics
  name: cassandra-analytics
spec:
  clusterIP: None
  ports:
    - port: 9042
  selector:
    app: cassandra-analytics
