apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra-single
spec:
  ports:
    - port: 9042
      protocol: TCP
  externalIPs:
    - 192.168.64.2
  selector:
    app: cassandra
