apiVersion: v1
kind: ReplicationController
metadata:
  name: pet-race-ui
spec:
  replicas: 200
  template:
    metadata:
      labels:
        app: pet-race-ui
        tier: frontend
    spec:
      containers:
      - name: pet-race-ui
        image: "gcr.io/aronchick-apollobit/pet-race-ui:v1.3"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "2"
            memory: 5Gi
          requests:
            cpu: "2"
            memory: 5Gi

