apiVersion: v1
kind: Service
metadata:
  name: pet-race-ui
  namespace: pet-race-ui
  labels:
    app: pet-race-ui
    tier: frontend
spec:
  ports:
    - port: 8080
  selector:
    app: pet-race-ui
    tier: frontend
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pet-race-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pet-race-ui
        tier: frontend
    spec:
      containers:
      - name: pet-race-ui
        image: "gcr.io/aronchick-apollobit/pet-race-ui:v1.1"
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "2"
            memory: 2Gi
