apiVersion: batch/v1
kind: Job
metadata:
  name: pet-race-giants
  labels:
    name: pet-races
spec:
  parallelism: 2
  completions: 4
  template:
    metadata:
      name: pet-race-giants
      labels:
        name: pet-races
    spec:
      containers:
      - name: pet-race-giants
        image: gcr.io/aronchick-apollobit/py3numpy-job-dev:v1.0
        command: ["pet-race-job", "--description=A_pet_race", "--length=100", "--pet=Giants", "--scale=3"]
        resources:
          limits:
            cpu: "2"
          requests:
            cpu: "2"
      restartPolicy: Never
