version: '2'
services:
    gpmr-app:
        image: gpmr
        external_links:
            - gpmr-cassandra:cassandra
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
        ports:
            - 8080:8080
    gpmr-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: gpmr-cassandra
